apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress-rc
  namespace: platform
  labels:
    app: nginx-ingress
spec:
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      hostNetwork: true
      restartPolicy: Always
      containers:
      - image: nginxdemos/nginx-ingress:0.6.0
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
        - containerPort: 443
          hostPort: 443
          name: https
        # Uncomment the lines below to enable extensive logging and/or customization of
        # NGINX configuration with configmaps
        args:
        - -v=3
        - -nginx-configmaps=default/nginx-config
